# auth-service.yml dans le dépôt Git du Config Server
server:
  port: 8004

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    # url: jdbc:mysql://root:ilIVViBStDbHESuBqyokHVMvDobsyGJN@maglev.proxy.rlwy.net:33278/railway
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    secret-key: b0b0f08db683aff4af2e942f90f2c1fbd844481a6e79cd98a06717b4af3b4f01
    expiration-time: 86400000